ARG ELASTIC_VERSION=8.5.3

# https://www.docker.elastic.co/
FROM elasticsearch:${ELASTIC_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
