{
 "title": "Golang Web API Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,2m,5m,10m,30m,1h,2h,3h,6h,12h,1d"
   },
   { "name": "status_code", "label": "status_code", "query": { "query": "label_values(status_code)" } },
   { "name": "path", "label": "path", "query": { "query": "label_values(path)" } },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "method", "label": "method", "query": { "query": "label_values(method)" } }
  ]
 },
 "panels": [
  {
   "title": "Service Error Percent",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_response_time_count{status_code!~\"(200|201)\",instance=~\"(192.168.1.114:5005|genx-api1:5000|genx-api2:5000)\"}[$interval])) / \nsum(increase(http_response_time_count{instance=~\"(192.168.1.114:5005|genx-api1:5000|genx-api2:5000)\"}[$interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Error Percent",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(db_calls_total{status=\"Failed\",instance=~\"(192.168.1.114:5005|genx-api1:5000|genx-api2:5000)\"}[$interval])) / \n(sum(increase(db_calls_total{instance=~\"(192.168.1.114:5005|genx-api1:5000|genx-api2:5000)\"}[$interval])) + 0.000000001)\n * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Thread Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Stat",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "round(sum by (instance)(increase(go_gc_duration_seconds_count{instance=~\"$instance\"}[$interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC average time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(go_gc_duration_seconds_sum{instance=~\"$instance\"}[$interval])) /\nsum by (instance) (rate(go_gc_duration_seconds_count{instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Time Heatmap",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (http_response_time_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_response_time_sum{path=~\"$path\",method=~\"$method\",status_code=~\"$status_code\"}[$interval])) /\nsum by (path) (rate(http_response_time_count{path=~\"$path\",method=~\"$method\",status_code=~\"$status_code\"}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Database Call Status",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 23, "x": 1, "y": 43 },
   "targets": [
    {
     "expr": "round(sum by (status) (increase(db_calls_total[$interval])))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}