// Functionality categories
export const FUNCTIONALITY_CATEGORIES = [
    "STANDARD",
    "CUSTOM",
] as const;

export type FunctionalityCategory = typeof FUNCTIONALITY_CATEGORIES[number];

// Functionality types
export const FUNCTIONALITY_TYPES = [
    "CACHE",
    "MESSAGE BROKER",
    "DATABASE",
    "LOGGING",
    "AUTHENTICATION",
    "AUTHORIZATION",
    "EMAIL SERVICE",
    "SMS SERVICE",
    "PUSH NOTIFICATION",
    "OBJECT STORAGE",
    "HTTP CLIENT",
    "JOB SCHEDULER",
    "SEARCH ENGINE",
    "INPUT VALIDATION",
    "OBSERVABILITY",
    "PAYMENT GATEWAY",
    "FILE PROCESSING",
    "API GATEWAY",
    "RATE LIMITING",
    "SESSION MANAGEMENT",
    "WEBSOCKET",
    "REAL-TIME MESSAGING",
    "PDF GENERATION",
    "IMAGE PROCESSING",
    "ENCRYPTION",
    "CONFIGURATION",
    "AUDIT LOGGING",
] as const;

export type FunctionalityType = typeof FUNCTIONALITY_TYPES[number];

// Provider mappings based on type
export const PROVIDERS_BY_TYPE: Record<string, string[]> = {
    "CACHE": ["REDIS", "MEMCACHED", "IN-MEMORY"],
    "MESSAGE BROKER": ["RABBITMQ", "KAFKA", "AWS SQS", "AZURE SERVICE BUS", "REDIS"],
    "DATABASE": ["MYSQL", "POSTGRESQL", "MONGODB", "MSSQL", "ORACLE", "CASSANDRA"],
    "LOGGING": ["DEFAULT"],
    "AUTHENTICATION": ["JWT", "ACTIVE DIRECTORY", "OAUTH2", "SAML", "FIREBASE AUTH", "AWS COGNITO"],
    "AUTHORIZATION": ["RBAC", "ABAC", "POLICY-BASED", "CUSTOM"],
    "EMAIL SERVICE": ["SENDGRID", "AWS SES", "MAILGUN", "SMTP", "POSTMARK"],
    "SMS SERVICE": ["TWILIO", "AWS SNS", "NEXMO", "MESSAGEBIRD"],
    "PUSH NOTIFICATION": ["FIREBASE", "AWS SNS", "ONESIGNAL", "PUSHWOOSH"],
    "OBJECT STORAGE": ["AZURE BLOB STORAGE", "AWS S3", "GOOGLE CLOUD STORAGE", "LOCAL STORAGE"],
    "HTTP CLIENT": ["DEFAULT"],
    "JOB SCHEDULER": ["DEFAULT"],
    "SEARCH ENGINE": ["ELASTICSEARCH", "ALGOLIA", "AZURE SEARCH", "SOLR"],
    "INPUT VALIDATION": ["MSISDN VALIDATOR", "EMAIL VALIDATOR", "REGEX VALIDATOR", "CUSTOM"],
    "OBSERVABILITY": ["OPENTELEMETRY", "DATADOG", "NEW RELIC", "APP INSIGHTS"],
    "PAYMENT GATEWAY": ["STRIPE", "PAYPAL", "SQUARE", "BRAINTREE", "FLUTTERWAVE", "PAYSTACK"],
    "FILE PROCESSING": ["DEFAULT"],
    "API GATEWAY": ["KONG", "AWS API GATEWAY", "AZURE API MANAGEMENT", "NGINX", "TRAEFIK"],
    "RATE LIMITING": ["REDIS", "IN-MEMORY", "NGINX", "CUSTOM"],
    "SESSION MANAGEMENT": ["REDIS", "MEMCACHED", "DATABASE", "IN-MEMORY"],
    "WEBSOCKET": ["SOCKET.IO", "SIGNALR", "WS", "DEFAULT"],
    "REAL-TIME MESSAGING": ["PUSHER", "ABLY", "PUBNUB", "SOCKET.IO"],
    "PDF GENERATION": ["DEFAULT"],
    "IMAGE PROCESSING": ["IMAGEMAGICK", "SHARP", "PILLOW", "DEFAULT"],
    "ENCRYPTION": ["AES", "RSA", "BCRYPT", "ARGON2", "DEFAULT"],
    "CONFIGURATION": ["ENVIRONMENT VARIABLES", "CONFIG SERVER", "AZURE APP CONFIG", "AWS PARAMETER STORE"],
    "AUDIT LOGGING": ["DATABASE", "ELASTICSEARCH", "CUSTOM"],
};

// Helper function to get providers for a type
export function getProvidersForType(type: string): string[] {
    return PROVIDERS_BY_TYPE[type] || [];
}
